apiVersion: bulward.io/v1alpha1
kind: OrganizationRoleTemplate
metadata:
  name: rbac-admin
spec:
  bindTo:
  - Owners
  scopes:
  - Organization
  rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - bind
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
