presubmits:
  - name: pull-kubermatic-bulward-validate-prow-yaml
    always_run: true
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/bulward.git
    extra_refs:
      - org: kubermatic
        repo: infra
        base_ref: master
        clone_uri: git@github.com:kubermatic/infra.git
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20200203-711d3732b
          command:
            - /app/prow/cmd/checkconfig/app.binary
          args:
            - --plugin-config=/home/prow/go/src/github.com/kubermatic/infra/prow/plugins.yaml
            - --config-path=/home/prow/go/src/github.com/kubermatic/infra/prow/config.yaml
            - --job-config-path=/home/prow/go/src/github.com/kubermatic/infra/prow/jobs
            - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)

  - name: pull-bulward-test
    always_run: true
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/bulward.git
    spec:
      containers:
        - image: quay.io/kubermatic/bulward-test
          imagePullPolicy: Always
          command:
            - make
            - test
          env:
            - name: GO111MODULE
              value: "on"
          resources:
            requests:
              cpu: 4

  - name: pull-bulward-lint
    always_run: true
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/bulward.git
    spec:
      containers:
        - image: quay.io/kubermatic/bulward-test
          imagePullPolicy: Always
          command:
            - make
            - lint
          env:
            - name: GO111MODULE
              value: "on"
              resources:
                requests:
                  cpu: 4
                  memory: 6Gi
  - name: post-bulward-test-image
    decorate: true
    clone_uri: ssh://git@github.com/kubermatic/bulward.git
    branches:
      - ^master$
    run_if_changed: "(go.sum|go.mod|test.Dockerfile|.pre-commit-config.yaml)"
    spec:
      containers:
        - image: quay.io/kubermatic/bulward-test
          imagePullPolicy: Always
          name: e2e-test
          command:
            - make
            - push-image-test
          env:
            - name: GO111MODULE
              value: "on"
            - name: QUAY_IO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubermatic-quay.io
                  key: username
            - name: QUAY_IO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubermatic-quay.io
                  key: password
          # docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 800m
              memory: 2Gi
