
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiserver.bulward.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bulward.io
  resources:
  - organizationroles
  verbs:
  - bind
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - bulward.io
  resources:
  - organizationroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bulward.io
  resources:
  - organizationroletemplates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - bulward.io
  resources:
  - organizationroletemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bulward.io
  resources:
  - projectroletemplates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - bulward.io
  resources:
  - projectroletemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.bulward.io
  resources:
  - organizations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.bulward.io
  resources:
  - organizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.bulward.io
  resources:
  - projects
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.bulward.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
