resources:
- manager.yaml
- service.yaml
- apiservice.yaml
configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: manager
  newName: quay.io/kubermatic/bulward-apiserver
  newTag: v1
