# This configuration is for teaching kustomize how to update name ref and var substitution
nameReference:
  - kind: Service
    version: v1
    fieldSpecs:
      - kind: APIService
        group: apiregistration.k8s.io
        path: spec/service/name

namespace:
  - kind: APIService
    group: apiregistration.k8s.io
    path: spec/service/namespace
    create: true
