#!/usr/bin/env bash

# Copyright 2020 The Bulward Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail
set -x

if [ -z $(go env GOBIN) ]; then
GOBIN=$(go env GOPATH)/bin
else
GOBIN=$(go env GOBIN)
fi

if [ -z "$(which controller-gen)" ]; then
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.9
  CONTROLLER_GEN=$GOBIN/controller-gen
else
  CONTROLLER_GEN=$(which controller-gen)
fi

CONTROLLER_GEN_VERSION=$(${CONTROLLER_GEN} --version)
CONTROLLER_GEN_WANT_VERSION="Version: v0.2.9"

if [[  ${CONTROLLER_GEN_VERSION} != "${CONTROLLER_GEN_WANT_VERSION}" ]]; then
  echo "Wrong controller-gen version. Wants ${CONTROLLER_GEN_WANT_VERSION} found ${CONTROLLER_GEN_VERSION}"
  exit 1
fi

CRD_VERSION="v1"
HEADER_FILE=./hack/boilerplate/boilerplate.go.txt

# Manager
# -------
# CRDs
$CONTROLLER_GEN crd:crdVersions=${CRD_VERSION} paths="./pkg/apis/core/..." output:crd:artifacts:config=config/manager/crd/bases
$CONTROLLER_GEN crd:crdVersions=${CRD_VERSION} paths="./pkg/apis/storage/..." output:crd:artifacts:config=config/manager/crd/bases
# Webhooks
$CONTROLLER_GEN webhook paths="./pkg/manager/internal/webhooks/..." output:webhook:artifacts:config=config/manager/webhook
# RBAC
$CONTROLLER_GEN rbac:roleName=manager-role paths="./pkg/manager/..." output:rbac:artifacts:config=config/manager/rbac


# Bulward API extension server
# RBAC
$CONTROLLER_GEN rbac:roleName=manager-role paths="./pkg/apiserver/..." output:rbac:artifacts:config=config/apiserver/rbac
# Generators for API extension server.
export GOROOT=$(go env GOROOT)
# We don't want to generate zz_generated.defaults.go for core api group.
defaulter-gen \
  --input-dirs k8c.io/bulward/pkg/apis/apiserver/v1alpha1 \
  --input-dirs k8c.io/bulward/pkg/apis/apiserver \
  --go-header-file ${HEADER_FILE}
openapi-gen \
  --input-dirs k8c.io/bulward/pkg/apis/apiserver/v1alpha1 \
  --input-dirs k8c.io/bulward/pkg/apis/storage/v1alpha1 \
  --input-dirs k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/version,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/util/intstr,k8s.io/api/core/v1,k8s.io/api/apps/v1,k8s.io/api/rbac/v1 \
  --go-header-file ${HEADER_FILE} \
  --output-package k8c.io/bulward/pkg/openapi
conversion-gen \
  --input-dirs k8c.io/bulward/pkg/apis/apiserver/v1alpha1 \
  --input-dirs k8c.io/bulward/pkg/apis/core/v1alpha1 \
  --input-dirs k8c.io/bulward/pkg/apis/storage/v1alpha1 \
  --input-dirs k8c.io/bulward/pkg/apis/apiserver \
  --input-dirs k8c.io/bulward/pkg/apis/core \
  --input-dirs k8c.io/bulward/pkg/apis/storage \
  --extra-peer-dirs k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
  --go-header-file ${HEADER_FILE} \
  -O zz_generated.conversion

goimports -local k8c.io/bulward -w .

# DeepCopy functions
# Run deepcopy-gen after all generators finish, otherwise the objects that are generated by conversion-gen will miss deepcopy functions.
$CONTROLLER_GEN "object:headerFile=./hack/boilerplate/boilerplate.go.txt,year=$(date +%Y)" paths=./pkg/apis/...
