### TODO: Find a way to use Kustomize to manage this config but not to override the namespace of this RoleBinding.
### Kustomize will override all namespace of all resources, so we decided to apply this RoleBinding manually, since this RoleBinding should be created in `kube-system` namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bulward::extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: bulward-apiserver-sa
  namespace: bulward-system
