apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bulward:user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bulward:user
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
